[package]
name = "glossary"
version = "0.1.1"
edition = "2021"
authors = ["Duyet <me@duyet.net>"]

[dependencies]
actix-cors = "0.6.1"
actix-web = "4.1.0"
actix-web-validator = "4.0.0"
ammonia = "3"
anyhow = "1.0.58"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1", features = ["postgres", "extras", "uuidv07"] }
diesel_migrations = "1.4.0"
dotenv = "0.15"
env_logger = "0.9"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"
uuid = { version = "0.8", features = ["serde", "v4"] }
validator = { version = "0.15.0", features = ["derive"] }

[dev-dependencies]
actix-rt = "2"
