[package]
name = "glossary"
version = "0.1.0"
edition = "2021"
authors = ["Duyet <me@duyet.net>"]

[dependencies]
actix-cors = "0.5"
actix-web = "4"
actix-web-validator = "2.2.0"
ammonia = "3"
anyhow = "1.0.55"
chrono = { version = "0.4", features = ["serde"] }
diesel = {version = "1", features = ["postgres", "extras"]}
diesel_migrations = "1.4.0"
dotenv = "0.15"
env_logger = "0.9"
log = "0.4"
serde = "1"
serde_json = "1.0.79"
thiserror = "1.0.30"
uuid = { version = "0.6", features = ["serde", "v4"] }
validator = { version = "0.12", features = ["derive"] }

[dev-dependencies]
actix-rt = "2"
